export type OrganId =
  | "heart"
  | "brain"
  | "lungs"
  | "liver"
  | "kidneys"
  | "eyeball"
  | "intestine"
  | "pancreas"
  | "skin";

export type Locale = "en" | "ar";

export type Hotspot = {
  id: string;
  label: string;
  detail: string;
  position: [number, number, number];
  color: string;
};

export type Organ = {
  id: OrganId;
  name: string;
  scientificName: string;
  system: string;
  model: string;
  icon: string;
  accent: string;
  description: string;
  poetic: string;
  size: string;
  weight: string;
  location: string;
  function: string;
  dailyFact: string;
  medical: string;
  bloodSupply: string;
  /** A single memorable line, surfaced as the "Did you know" note. */
  funFact: string;
  tissue: string;
  comparison: string;
  conditions: string[];
  hotspots: Hotspot[];
  /** Whether `/anatomy/<id>/*.webp` illustrations exist. Organs without them
   *  fall back to the accent glyph rather than a broken image. */
  illustrated: boolean;
};

const organsEn: Organ[] = [
  {
    id: "heart",
    name: "Heart",
    scientificName: "Cor",
    system: "Cardiovascular",
    model: "/models/heart.glb",
    icon: "♥",
    accent: "#ee7c6a",
    description: "A muscular organ that pumps blood throughout the body, delivering oxygen and nutrients to every cell.",
    poetic: "The tireless pump",
    size: "About the size of your fist",
    weight: "250–350 g",
    location: "Behind the sternum, slightly left",
    function: "Circulates oxygenated blood",
    dailyFact: "Beats about 100,000 times",
    medical: "Its electrical rhythm coordinates every heartbeat.",
    bloodSupply: "Left and right coronary arteries",
    funFact: "It beats roughly 2.5 billion times in an average lifetime, and starts before you are born.",
    tissue: "Cardiac muscle tissue",
    comparison: "Heart vs. brain",
    conditions: ["Coronary artery disease", "Arrhythmia", "Heart valve disorders", "Heart failure", "Cardiomyopathy", "Myocarditis", "Atrial fibrillation", "Congenital heart defects"],
    illustrated: true,
    hotspots: [
      { id: "aorta", label: "Aorta", detail: "Main artery", position: [-0.35, 1.65, 0.55], color: "#ee7c6a" },
      { id: "left-atrium", label: "Left Atrium", detail: "Receives oxygenated blood", position: [0.82, 0.65, 0.5], color: "#f2a33b" },
      { id: "right-atrium", label: "Right Atrium", detail: "Receives venous blood", position: [-0.9, 0.35, 0.55], color: "#6393d8" },
      { id: "left-ventricle", label: "Left Ventricle", detail: "Pumps to the body", position: [0.7, -0.75, 0.65], color: "#f2a33b" },
      { id: "right-ventricle", label: "Right Ventricle", detail: "Pumps to the lungs", position: [-0.65, -0.68, 0.66], color: "#ee7c6a" },
      { id: "mitral", label: "Mitral Valve", detail: "Prevents backflow", position: [0.18, -1.35, 0.48], color: "#d89bc4" },
    ],
  },
  {
    id: "brain",
    name: "Brain",
    scientificName: "Encephalon",
    system: "Nervous System",
    model: "/models/brain.glb",
    icon: "◉",
    accent: "#c58696",
    description: "The body’s command center, integrating sensation, memory, emotion, and precise movement.",
    poetic: "The universe within",
    size: "Roughly two clenched fists",
    weight: "1.3–1.4 kg",
    location: "Protected within the skull",
    function: "Processes and coordinates signals",
    dailyFact: "Uses about 20% of the body’s energy",
    medical: "Billions of neurons communicate through electrical and chemical signals.",
    bloodSupply: "Internal carotid and vertebral arteries",
    funFact: "It has no pain receptors of its own — a headache is felt in the tissues around it.",
    tissue: "Cerebral cortex",
    comparison: "Brain vs. eye",
    conditions: ["Migraine", "Stroke", "Neurodegenerative disease", "Epilepsy", "Traumatic brain injury", "Meningitis", "Multiple sclerosis", "Brain aneurysm"],
    illustrated: true,
    hotspots: [
      { id: "frontal", label: "Frontal Lobe", detail: "Planning & movement", position: [-0.7, 0.65, 0.8], color: "#ee7c6a" },
      { id: "parietal", label: "Parietal Lobe", detail: "Sensory integration", position: [0.15, 1.1, 0.65], color: "#f2a33b" },
      { id: "temporal", label: "Temporal Lobe", detail: "Memory & hearing", position: [0.75, -0.1, 0.82], color: "#6393d8" },
      { id: "cerebellum", label: "Cerebellum", detail: "Balance & coordination", position: [0.72, -0.9, 0.55], color: "#d89bc4" },
    ],
  },
  {
    id: "lungs",
    name: "Lungs",
    scientificName: "Pulmones",
    system: "Respiratory System",
    model: "/models/lungs.glb",
    icon: "◍",
    accent: "#dd8f8b",
    description: "Paired organs that draw in air and trade oxygen for carbon dioxide across a vast, delicate surface.",
    poetic: "The breath of life",
    size: "Each about 25 cm tall",
    weight: "About 1 kg for the pair",
    location: "Either side of the heart, within the ribcage",
    function: "Exchanges oxygen for carbon dioxide",
    dailyFact: "Moves around 11,000 L of air",
    medical: "Alveoli fold a tennis-court-sized exchange surface into the chest.",
    bloodSupply: "Pulmonary and bronchial arteries",
    funFact: "The right lung carries three lobes and the left only two, leaving a notch for the heart.",
    tissue: "Alveolar tissue",
    comparison: "Lungs vs. heart",
    conditions: ["Asthma", "COPD", "Pneumonia", "Pulmonary embolism", "Pulmonary fibrosis", "Bronchitis", "Cystic fibrosis", "Lung cancer"],
    illustrated: true,
    hotspots: [
      { id: "trachea", label: "Trachea", detail: "Carries air to the lungs", position: [0, 1.6, 0.2], color: "#6393d8" },
      { id: "right-lung", label: "Right Lung", detail: "Three lobes", position: [-1.2, 0.1, 0.7], color: "#ee7c6a" },
      { id: "left-lung", label: "Left Lung", detail: "Two lobes, room for the heart", position: [1.2, 0.1, 0.7], color: "#f2a33b" },
      { id: "bronchus", label: "Bronchus", detail: "Branching airway", position: [-0.03, 0.3, 0.35], color: "#d89bc4" },
      { id: "base", label: "Lung Base", detail: "Rests on the diaphragm", position: [-1.14, -1.2, 1], color: "#7fa88a" },
    ],
  },
  {
    id: "liver",
    name: "Liver",
    scientificName: "Hepar",
    system: "Digestive System",
    model: "/models/liver.glb",
    icon: "≈",
    accent: "#b86858",
    description: "A remarkable metabolic organ that filters blood, processes nutrients, and produces bile.",
    poetic: "The quiet alchemist",
    size: "About the size of a football",
    weight: "1.4–1.6 kg",
    location: "Upper right abdomen",
    function: "Metabolism, detoxification & bile",
    dailyFact: "Performs more than 500 functions",
    medical: "It can regenerate a substantial portion of lost tissue.",
    bloodSupply: "Hepatic artery and portal vein",
    funFact: "It is the only human organ that can regrow to full size from a fraction of itself.",
    tissue: "Hepatic lobules",
    comparison: "Liver vs. intestine",
    conditions: ["Fatty liver disease", "Hepatitis", "Cirrhosis", "Gallstones", "Haemochromatosis", "Liver cancer", "Autoimmune hepatitis", "Portal hypertension"],
    illustrated: true,
    hotspots: [
      { id: "right-lobe", label: "Right Lobe", detail: "Largest hepatic lobe", position: [-0.75, 0.35, 0.75], color: "#ee7c6a" },
      { id: "left-lobe", label: "Left Lobe", detail: "Crosses the midline", position: [0.85, 0.25, 0.75], color: "#f2a33b" },
      { id: "portal", label: "Portal Vein", detail: "Nutrient-rich inflow", position: [0.1, -0.3, 0.82], color: "#6393d8" },
    ],
  },
  {
    id: "kidneys",
    name: "Kidneys",
    scientificName: "Renes",
    system: "Urinary System",
    model: "/models/kidneys.glb",
    icon: "∞",
    accent: "#c96963",
    description: "Paired filtration organs that balance fluids, electrolytes, blood pressure, and waste removal.",
    poetic: "The master filters",
    size: "Each is about a computer mouse",
    weight: "120–170 g each",
    location: "Either side of the spine below the ribs",
    function: "Filters blood and forms urine",
    dailyFact: "Filters roughly 180 L of fluid",
    medical: "Nephrons fine-tune the chemistry of the bloodstream.",
    bloodSupply: "Renal arteries",
    funFact: "They reclaim almost everything they filter — only about 1–2 L leaves the body as urine.",
    tissue: "Renal cortex",
    comparison: "Kidneys vs. liver",
    conditions: ["Kidney stones", "Chronic kidney disease", "Urinary infection", "Glomerulonephritis", "Polycystic kidney disease", "Renal hypertension", "Acute kidney injury", "Nephrotic syndrome"],
    illustrated: true,
    hotspots: [
      { id: "cortex", label: "Renal Cortex", detail: "Outer filtering layer", position: [-0.9, 0.55, 0.7], color: "#ee7c6a" },
      { id: "medulla", label: "Renal Medulla", detail: "Concentrates urine", position: [0.85, 0.2, 0.7], color: "#f2a33b" },
      { id: "ureter", label: "Ureter", detail: "Carries urine", position: [0.4, -1.1, 0.5], color: "#6393d8" },
    ],
  },
  {
    id: "eyeball",
    name: "Eye",
    scientificName: "Oculus",
    system: "Sensory System",
    model: "/models/eyeball.glb",
    icon: "⊙",
    accent: "#7294b9",
    description: "A precision sensory organ that converts focused light into neural signals interpreted as vision.",
    poetic: "A window made of light",
    size: "About 24 mm across",
    weight: "Around 7.5 g",
    location: "Within the bony orbit",
    function: "Captures and focuses light",
    dailyFact: "Makes thousands of tiny movements",
    medical: "The retina is an extension of the central nervous system.",
    bloodSupply: "Ophthalmic artery",
    funFact: "The cornea carries no blood vessels at all; it takes oxygen directly from the air.",
    tissue: "Retinal layers",
    comparison: "Eye vs. brain",
    conditions: ["Myopia", "Cataract", "Glaucoma", "Macular degeneration", "Retinal detachment", "Dry eye disease", "Astigmatism", "Conjunctivitis"],
    illustrated: true,
    hotspots: [
      { id: "cornea", label: "Cornea", detail: "Clear focusing surface", position: [-0.94, 0.05, 1.47], color: "#6393d8" },
      { id: "iris", label: "Iris", detail: "Controls light entry", position: [-1.22, -0.53, 1.15], color: "#f2a33b" },
      { id: "optic", label: "Optic Nerve", detail: "Carries visual signals", position: [1.61, -0.18, 0.54], color: "#d89bc4" },
    ],
  },
  {
    id: "intestine",
    name: "Intestine",
    scientificName: "Intestinum",
    system: "Digestive System",
    model: "/models/intestine.glb",
    icon: "§",
    accent: "#d78b77",
    description: "A folded digestive passage where nutrients are absorbed and the microbiome supports whole-body health.",
    poetic: "The inner garden",
    size: "About 6–7 m when extended",
    weight: "Varies with contents",
    location: "Central and lower abdomen",
    function: "Digestion and nutrient absorption",
    dailyFact: "Hosts trillions of microorganisms",
    medical: "Its surface is amplified by folds, villi, and microvilli.",
    bloodSupply: "Superior and inferior mesenteric arteries",
    funFact: "Its lining renews itself every few days — the fastest turnover of any tissue in the body.",
    tissue: "Intestinal villi",
    comparison: "Intestine vs. liver",
    conditions: ["Irritable bowel syndrome", "Inflammatory bowel disease", "Celiac disease", "Diverticulitis", "Intestinal obstruction", "Colorectal polyps", "Crohn's disease", "Lactose intolerance"],
    illustrated: true,
    hotspots: [
      { id: "duodenum", label: "Duodenum", detail: "First small-intestine segment", position: [0.6, 0.8, 0.75], color: "#f2a33b" },
      { id: "jejunum", label: "Jejunum", detail: "Major absorption region", position: [-0.45, 0.1, 0.82], color: "#ee7c6a" },
      { id: "colon", label: "Colon", detail: "Reclaims water", position: [0.75, -0.55, 0.72], color: "#6393d8" },
    ],
  },
  {
    id: "pancreas",
    name: "Pancreas",
    scientificName: "Pancreas",
    system: "Endocrine System",
    model: "/models/pancreas.glb",
    icon: "◈",
    accent: "#c69a5e",
    description: "A dual-purpose gland that releases digestive enzymes into the gut and the hormones that steady blood sugar.",
    poetic: "The quiet regulator",
    size: "About 15 cm long",
    weight: "70–100 g",
    location: "Behind the stomach, across the upper abdomen",
    function: "Digestive enzymes and insulin",
    dailyFact: "Makes about 1.5 L of enzyme-rich juice",
    medical: "Islets of Langerhans release insulin and glucagon to balance blood sugar.",
    bloodSupply: "Splenic and pancreaticoduodenal arteries",
    funFact: "Barely 2% of it makes hormones; the rest is given over to digestive enzymes.",
    tissue: "Pancreatic acini",
    comparison: "Pancreas vs. liver",
    conditions: ["Pancreatitis", "Type 1 diabetes", "Pancreatic cancer", "Type 2 diabetes", "Exocrine insufficiency", "Pancreatic cysts", "Gallstone pancreatitis", "Insulinoma"],
    illustrated: true,
    hotspots: [
      { id: "head", label: "Head", detail: "Cradled by the duodenum", position: [-1.32, -0.36, 0.55], color: "#ee7c6a" },
      { id: "body", label: "Body", detail: "Crosses the spine", position: [0.05, 0.25, 0.45], color: "#f2a33b" },
      { id: "tail", label: "Tail", detail: "Reaches the spleen", position: [1.55, 0.3, 0.35], color: "#6393d8" },
      { id: "duct", label: "Pancreatic Duct", detail: "Drains enzymes to the gut", position: [-0.61, 0.39, 0.5], color: "#d89bc4" },
    ],
  },
  {
    id: "skin",
    name: "Skin",
    scientificName: "Integumentum",
    system: "Integumentary System",
    model: "/models/skin.glb",
    icon: "▦",
    accent: "#c99277",
    description: "The body’s largest organ — a living barrier that senses touch, holds in water, and regulates temperature.",
    poetic: "The living boundary",
    size: "About 2 m² spread flat",
    weight: "3.5–5 kg",
    location: "Covering the entire body",
    function: "Protects, senses, and cools",
    dailyFact: "Sheds around 500 million cells",
    medical: "Three layers — epidermis, dermis, and hypodermis — each with a distinct job.",
    bloodSupply: "Dermal vascular plexus",
    funFact: "A single square centimetre can hold hundreds of sweat glands and metres of blood vessels.",
    tissue: "Epidermal layers",
    comparison: "Skin vs. intestine",
    conditions: ["Eczema", "Psoriasis", "Melanoma", "Acne vulgaris", "Cellulitis", "Contact dermatitis", "Rosacea", "Vitiligo"],
    illustrated: true,
    hotspots: [
      { id: "epidermis", label: "Epidermis", detail: "Outer protective layer", position: [-0.05, 0.88, 1.4], color: "#ee7c6a" },
      { id: "dermis", label: "Dermis", detail: "Nerves, vessels & glands", position: [0.29, 0.05, 1.4], color: "#f2a33b" },
      { id: "hypodermis", label: "Hypodermis", detail: "Fat and insulation", position: [-0.39, -1.15, 1.4], color: "#6393d8" },
      { id: "follicle", label: "Hair Follicle", detail: "Anchors each hair", position: [0.89, -0.44, 1.4], color: "#d89bc4" },
    ],
  },
];

const organsAr: Organ[] = [
  {
    id: "heart",
    name: "القلب",
    scientificName: "Cor",
    system: "الجهاز الدوري",
    model: "/models/heart.glb",
    icon: "♥",
    accent: "#ee7c6a",
    description: "عضو عضلي يضخّ الدم عبر الجسم بأكمله، ناقلاً الأكسجين والعناصر الغذائية إلى كل خلية.",
    poetic: "المِضخّة التي لا تكِلّ",
    size: "بحجم قبضة يدك تقريباً",
    weight: "٢٥٠–٣٥٠ غراماً",
    location: "خلف عظمة القص، يميل قليلاً لليسار",
    function: "يُدوّر الدم المؤكسج في الجسم",
    dailyFact: "ينبض نحو ١٠٠,٠٠٠ مرة يومياً",
    medical: "إيقاعه الكهربائي ينسّق كل نبضة قلب.",
    bloodSupply: "الشريانان التاجيان الأيمن والأيسر",
    funFact: "ينبض نحو 2.5 مليار مرة خلال متوسط العمر، ويبدأ النبض قبل الولادة.",
    tissue: "النسيج العضلي القلبي",
    comparison: "القلب مقابل الدماغ",
    conditions: ["مرض الشريان التاجي", "اضطراب النظم القلبي", "أمراض صمامات القلب", "قصور القلب", "اعتلال عضلة القلب", "التهاب عضلة القلب", "الرجفان الأذيني", "عيوب القلب الخلقية"],
    illustrated: true,
    hotspots: [
      { id: "aorta", label: "الأبهر", detail: "الشريان الرئيسي", position: [-0.35, 1.65, 0.55], color: "#ee7c6a" },
      { id: "left-atrium", label: "الأذين الأيسر", detail: "يستقبل الدم المؤكسج", position: [0.82, 0.65, 0.5], color: "#f2a33b" },
      { id: "right-atrium", label: "الأذين الأيمن", detail: "يستقبل الدم الوريدي", position: [-0.9, 0.35, 0.55], color: "#6393d8" },
      { id: "left-ventricle", label: "البطين الأيسر", detail: "يضخّ الدم إلى الجسم", position: [0.7, -0.75, 0.65], color: "#f2a33b" },
      { id: "right-ventricle", label: "البطين الأيمن", detail: "يضخّ الدم إلى الرئتين", position: [-0.65, -0.68, 0.66], color: "#ee7c6a" },
      { id: "mitral", label: "الصمام التاجي", detail: "يمنع الارتجاع", position: [0.18, -1.35, 0.48], color: "#d89bc4" },
    ],
  },
  {
    id: "brain",
    name: "الدماغ",
    scientificName: "Encephalon",
    system: "الجهاز العصبي",
    model: "/models/brain.glb",
    icon: "◉",
    accent: "#c58696",
    description: "مركز القيادة في الجسم، يدمج الإحساس والذاكرة والعاطفة والحركة الدقيقة.",
    poetic: "الكون الداخلي",
    size: "بحجم قبضتَي يد تقريباً",
    weight: "١.٣–١.٤ كغم",
    location: "محمي داخل الجمجمة",
    function: "يعالج الإشارات وينسّقها",
    dailyFact: "يستهلك نحو ٢٠٪ من طاقة الجسم",
    medical: "مليارات الخلايا العصبية تتواصل عبر إشارات كهربائية وكيميائية.",
    bloodSupply: "الشرايين السباتية الداخلية والفقرية",
    funFact: "لا يحتوي على مستقبِلات ألم خاصة به — يُستشعر الصداع في الأنسجة المحيطة به.",
    tissue: "القشرة الدماغية",
    comparison: "الدماغ مقابل العين",
    conditions: ["الصداع النصفي", "السكتة الدماغية", "الأمراض التنكسية العصبية", "الصرع", "إصابة الدماغ الرضحية", "التهاب السحايا", "التصلب المتعدد", "تمدد الأوعية الدموية الدماغية"],
    illustrated: true,
    hotspots: [
      { id: "frontal", label: "الفص الجبهي", detail: "التخطيط والحركة", position: [-0.7, 0.65, 0.8], color: "#ee7c6a" },
      { id: "parietal", label: "الفص الجداري", detail: "الدمج الحسي", position: [0.15, 1.1, 0.65], color: "#f2a33b" },
      { id: "temporal", label: "الفص الصدغي", detail: "الذاكرة والسمع", position: [0.75, -0.1, 0.82], color: "#6393d8" },
      { id: "cerebellum", label: "المخيخ", detail: "التوازن والتناسق", position: [0.72, -0.9, 0.55], color: "#d89bc4" },
    ],
  },
  {
    id: "lungs",
    name: "الرئتان",
    scientificName: "Pulmones",
    system: "الجهاز التنفسي",
    model: "/models/lungs.glb",
    icon: "◍",
    accent: "#dd8f8b",
    description: "عضوان مزدوجان يسحبان الهواء ويبادلان الأكسجين بثاني أكسيد الكربون عبر سطح واسع ورقيق.",
    poetic: "نَفَس الحياة",
    size: "كل رئة بطول ٢٥ سم تقريباً",
    weight: "نحو ١ كغم للزوج",
    location: "على جانبَي القلب، داخل القفص الصدري",
    function: "يبادلان الأكسجين بثاني أكسيد الكربون",
    dailyFact: "تحرّكان نحو ١١,٠٠٠ لتر من الهواء يومياً",
    medical: "تطوي الحويصلات الهوائية سطح تبادل بحجم ملعب تنس داخل الصدر.",
    bloodSupply: "الشرايين الرئوية والقصبية",
    funFact: "تحتوي الرئة اليمنى على ثلاثة فصوص بينما تحتوي اليسرى على فصين فقط، تاركةً مكاناً للقلب.",
    tissue: "النسيج الحويصلي",
    comparison: "الرئتان مقابل القلب",
    conditions: ["الربو", "مرض الانسداد الرئوي المزمن", "الالتهاب الرئوي", "الانصمام الرئوي", "التليف الرئوي", "التهاب الشعب الهوائية", "التليف الكيسي", "سرطان الرئة"],
    illustrated: true,
    hotspots: [
      { id: "trachea", label: "القصبة الهوائية", detail: "توصل الهواء إلى الرئتين", position: [0, 1.6, 0.2], color: "#6393d8" },
      { id: "right-lung", label: "الرئة اليمنى", detail: "ثلاثة فصوص", position: [-1.2, 0.1, 0.7], color: "#ee7c6a" },
      { id: "left-lung", label: "الرئة اليسرى", detail: "فصان، مكان للقلب", position: [1.2, 0.1, 0.7], color: "#f2a33b" },
      { id: "bronchus", label: "القصبة", detail: "مجرى هوائي متفرّع", position: [-0.03, 0.3, 0.35], color: "#d89bc4" },
      { id: "base", label: "قاعدة الرئة", detail: "ترتكز على الحجاب الحاجز", position: [-1.14, -1.2, 1], color: "#7fa88a" },
    ],
  },
  {
    id: "liver",
    name: "الكبد",
    scientificName: "Hepar",
    system: "الجهاز الهضمي",
    model: "/models/liver.glb",
    icon: "≈",
    accent: "#b86858",
    description: "عضو استقلابي مذهل يُصفّي الدم، ويعالج العناصر الغذائية، وينتج الصفراء.",
    poetic: "الكيميائي الصامت",
    size: "بحجم كرة القدم تقريباً",
    weight: "١.٤–١.٦ كغم",
    location: "أعلى يمين البطن",
    function: "الاستقلاب، وإزالة السموم، وإنتاج الصفراء",
    dailyFact: "يؤدي أكثر من ٥٠٠ وظيفة",
    medical: "يستطيع تجديد جزء كبير من نسيجه المفقود.",
    bloodSupply: "الشريان الكبدي والوريد البابي",
    funFact: "هو العضو البشري الوحيد القادر على النمو مجدداً إلى حجمه الكامل من جزء صغير منه.",
    tissue: "الفصيصات الكبدية",
    comparison: "الكبد مقابل الأمعاء",
    conditions: ["الكبد الدهني", "التهاب الكبد", "تليّف الكبد", "حصى المرارة", "داء ترسّب الأصبغة الدموية", "سرطان الكبد", "التهاب الكبد المناعي الذاتي", "ارتفاع ضغط الوريد البابي"],
    illustrated: true,
    hotspots: [
      { id: "right-lobe", label: "الفص الأيمن", detail: "أكبر فصوص الكبد", position: [-0.75, 0.35, 0.75], color: "#ee7c6a" },
      { id: "left-lobe", label: "الفص الأيسر", detail: "يعبر خط الوسط", position: [0.85, 0.25, 0.75], color: "#f2a33b" },
      { id: "portal", label: "الوريد البابي", detail: "تدفق غني بالعناصر الغذائية", position: [0.1, -0.3, 0.82], color: "#6393d8" },
    ],
  },
  {
    id: "kidneys",
    name: "الكليتان",
    scientificName: "Renes",
    system: "الجهاز البولي",
    model: "/models/kidneys.glb",
    icon: "∞",
    accent: "#c96963",
    description: "عضوان مزدوجان للترشيح، يوازنان السوائل والشوارد وضغط الدم والتخلص من الفضلات.",
    poetic: "المرشِّحان الرئيسيان",
    size: "كل كلية بحجم فأرة الحاسوب تقريباً",
    weight: "١٢٠–١٧٠ غراماً لكل كلية",
    location: "على جانبَي العمود الفقري أسفل الأضلاع",
    function: "يرشّحان الدم ويكوّنان البول",
    dailyFact: "يرشّحان نحو ١٨٠ لتراً من السوائل يومياً",
    medical: "النِّفرونات تضبط بدقة كيمياء مجرى الدم.",
    bloodSupply: "الشرايين الكلوية",
    funFact: "تستعيدان تقريباً كل ما يُرشَّح — لا يغادر الجسم كبول سوى لتر إلى لترين فقط.",
    tissue: "القشرة الكلوية",
    comparison: "الكليتان مقابل الكبد",
    conditions: ["حصى الكلى", "مرض الكلى المزمن", "التهاب المسالك البولية", "التهاب كبيبات الكلى", "مرض الكلى متعدد الكيسات", "ارتفاع ضغط الدم الكلوي", "الإصابة الكلوية الحادة", "المتلازمة الكلوية"],
    illustrated: true,
    hotspots: [
      { id: "cortex", label: "القشرة الكلوية", detail: "الطبقة الخارجية المرشِّحة", position: [-0.9, 0.55, 0.7], color: "#ee7c6a" },
      { id: "medulla", label: "لُبّ الكلية", detail: "يركّز البول", position: [0.85, 0.2, 0.7], color: "#f2a33b" },
      { id: "ureter", label: "الحالب", detail: "ينقل البول", position: [0.4, -1.1, 0.5], color: "#6393d8" },
    ],
  },
  {
    id: "eyeball",
    name: "العين",
    scientificName: "Oculus",
    system: "الجهاز الحسي",
    model: "/models/eyeball.glb",
    icon: "⊙",
    accent: "#7294b9",
    description: "عضو حسي دقيق يحوّل الضوء المُركَّز إلى إشارات عصبية تُفسَّر كرؤية.",
    poetic: "نافذة من ضوء",
    size: "نحو ٢٤ ملم قطراً",
    weight: "نحو ٧.٥ غرام",
    location: "داخل التجويف العظمي للعين",
    function: "يلتقط الضوء ويركّزه",
    dailyFact: "تقوم بآلاف الحركات الدقيقة يومياً",
    medical: "الشبكية امتداد للجهاز العصبي المركزي.",
    bloodSupply: "الشريان العيني",
    funFact: "القرنية لا تحتوي على أوعية دموية إطلاقاً؛ فهي تأخذ الأكسجين مباشرة من الهواء.",
    tissue: "طبقات الشبكية",
    comparison: "العين مقابل الدماغ",
    conditions: ["قصر النظر", "الساد (الكتاراكت)", "الزرق (الجلوكوما)", "التنكس البقعي", "انفصال الشبكية", "جفاف العين", "الاستجماتيزم", "التهاب الملتحمة"],
    illustrated: true,
    hotspots: [
      { id: "cornea", label: "القرنية", detail: "السطح الشفاف للتركيز", position: [-0.94, 0.05, 1.47], color: "#6393d8" },
      { id: "iris", label: "القزحية", detail: "تتحكم في دخول الضوء", position: [-1.22, -0.53, 1.15], color: "#f2a33b" },
      { id: "optic", label: "العصب البصري", detail: "ينقل الإشارات البصرية", position: [1.61, -0.18, 0.54], color: "#d89bc4" },
    ],
  },
  {
    id: "intestine",
    name: "الأمعاء",
    scientificName: "Intestinum",
    system: "الجهاز الهضمي",
    model: "/models/intestine.glb",
    icon: "§",
    accent: "#d78b77",
    description: "ممر هضمي متعرّج تُمتَص فيه العناصر الغذائية، ويدعم فيه الميكروبيوم صحة الجسم بأكمله.",
    poetic: "الحديقة الداخلية",
    size: "نحو ٦–٧ أمتار عند التمدد",
    weight: "يختلف حسب المحتوى",
    location: "وسط وأسفل البطن",
    function: "الهضم وامتصاص العناصر الغذائية",
    dailyFact: "يستضيف تريليونات الكائنات الدقيقة",
    medical: "تتضخم مساحة سطحه بفضل الطيّات والزغابات والزُّغيبات الدقيقة.",
    bloodSupply: "الشرايين المساريقية العلوية والسفلية",
    funFact: "تتجدد بطانته كل بضعة أيام — وهي الأسرع تجدداً بين أنسجة الجسم.",
    tissue: "زغابات الأمعاء",
    comparison: "الأمعاء مقابل الكبد",
    conditions: ["متلازمة القولون العصبي", "مرض الأمعاء الالتهابي", "الداء الزلاقي", "التهاب الرتوج", "انسداد الأمعاء", "الأورام الحميدة القولونية", "داء كرون", "عدم تحمل اللاكتوز"],
    illustrated: true,
    hotspots: [
      { id: "duodenum", label: "الاثنا عشر", detail: "أول جزء من الأمعاء الدقيقة", position: [0.6, 0.8, 0.75], color: "#f2a33b" },
      { id: "jejunum", label: "الصائم", detail: "منطقة الامتصاص الرئيسية", position: [-0.45, 0.1, 0.82], color: "#ee7c6a" },
      { id: "colon", label: "القولون", detail: "يستعيد الماء", position: [0.75, -0.55, 0.72], color: "#6393d8" },
    ],
  },
  {
    id: "pancreas",
    name: "البنكرياس",
    scientificName: "Pancreas",
    system: "الجهاز الصماوي",
    model: "/models/pancreas.glb",
    icon: "◈",
    accent: "#c69a5e",
    description: "غدة مزدوجة الوظيفة تفرز إنزيمات هضمية في الأمعاء وهرمونات تضبط سكر الدم.",
    poetic: "المنظِّم الصامت",
    size: "نحو ١٥ سم طولاً",
    weight: "٧٠–١٠٠ غراماً",
    location: "خلف المعدة، عبر أعلى البطن",
    function: "إنزيمات هضمية وأنسولين",
    dailyFact: "يفرز نحو ١.٥ لتر من العصارة الغنية بالإنزيمات",
    medical: "جزر لانغرهانس تفرز الأنسولين والغلوكاغون لموازنة سكر الدم.",
    bloodSupply: "الشريان الطحالي وشرايين الاثنا عشري البنكرياسية",
    funFact: "بالكاد ٢٪ منه يُنتج الهرمونات؛ والباقي مخصص للإنزيمات الهضمية.",
    tissue: "عُنيبات البنكرياس",
    comparison: "البنكرياس مقابل الكبد",
    conditions: ["التهاب البنكرياس", "السكري من النوع الأول", "سرطان البنكرياس", "السكري من النوع الثاني", "قصور البنكرياس الإفرازي", "أكياس البنكرياس", "التهاب البنكرياس الحصوي", "ورم الأنسولين"],
    illustrated: true,
    hotspots: [
      { id: "head", label: "الرأس", detail: "يحتضنه الاثنا عشر", position: [-1.32, -0.36, 0.55], color: "#ee7c6a" },
      { id: "body", label: "الجسم", detail: "يعبر العمود الفقري", position: [0.05, 0.25, 0.45], color: "#f2a33b" },
      { id: "tail", label: "الذيل", detail: "يمتد إلى الطحال", position: [1.55, 0.3, 0.35], color: "#6393d8" },
      { id: "duct", label: "القناة البنكرياسية", detail: "تصرّف الإنزيمات إلى الأمعاء", position: [-0.61, 0.39, 0.5], color: "#d89bc4" },
    ],
  },
  {
    id: "skin",
    name: "الجلد",
    scientificName: "Integumentum",
    system: "الجهاز الجلدي",
    model: "/models/skin.glb",
    icon: "▦",
    accent: "#c99277",
    description: "أكبر أعضاء الجسم — حاجز حيّ يستشعر اللمس، ويحفظ الماء، وينظّم درجة الحرارة.",
    poetic: "الحدود الحيّة",
    size: "نحو مترَين مربعين عند الفرد",
    weight: "٣.٥–٥ كغم",
    location: "يغطي الجسم بأكمله",
    function: "يحمي، ويستشعر، ويبرّد",
    dailyFact: "يتساقط منه نحو ٥٠٠ مليون خلية يومياً",
    medical: "ثلاث طبقات — البشرة والأدمة وتحت الجلد — لكل منها وظيفة مميزة.",
    bloodSupply: "الضفيرة الوعائية الأدمية",
    funFact: "يمكن لسنتيمتر مربّع واحد أن يحوي مئات الغدد العرقية وأمتاراً من الأوعية الدموية.",
    tissue: "طبقات البشرة",
    comparison: "الجلد مقابل الأمعاء",
    conditions: ["الأكزيما", "الصدفية", "الميلانوما", "حب الشباب الشائع", "التهاب النسيج الخلوي", "التهاب الجلد التماسي", "الوردية", "البهاق"],
    illustrated: true,
    hotspots: [
      { id: "epidermis", label: "البشرة", detail: "الطبقة الواقية الخارجية", position: [-0.05, 0.88, 1.4], color: "#ee7c6a" },
      { id: "dermis", label: "الأدمة", detail: "أعصاب وأوعية وغدد", position: [0.29, 0.05, 1.4], color: "#f2a33b" },
      { id: "hypodermis", label: "تحت الجلد", detail: "دهون وعزل حراري", position: [-0.39, -1.15, 1.4], color: "#6393d8" },
      { id: "follicle", label: "بصيلة الشعر", detail: "ترسّخ كل شعرة", position: [0.89, -0.44, 1.4], color: "#d89bc4" },
    ],
  },
];

export const organsByLocale: Record<Locale, Organ[]> = { en: organsEn, ar: organsAr };

export function getOrgans(locale: Locale): Organ[] {
  return organsByLocale[locale];
}

export function getOrganMap(locale: Locale): Record<OrganId, Organ> {
  return Object.fromEntries(organsByLocale[locale].map((organ) => [organ.id, organ])) as Record<OrganId, Organ>;
}
